# Generated by Django 5.0.3 on 2024-03-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_alter_users_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
        migrations.RemoveField(
            model_name='location',
            name='technician_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='store.location'),
        ),
    ]
