# Generated by Django 5.0.3 on 2024-04-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_delete_coordinator_delete_technician_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Optometry',
        ),
    ]
