# Generated by Django 5.0.3 on 2024-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_delete_optometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='registration',
            field=models.BooleanField(default=False),
        ),
    ]
