# Generated by Django 5.0.3 on 2024-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_remove_users_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='xrai_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
