# Generated by Django 5.0.3 on 2024-05-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_users_xrai_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='patient_id',
            field=models.CharField(default=0, max_length=100, null=True, unique=True),
        ),
    ]
