# Generated by Django 5.0.3 on 2024-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_alter_users_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='drconsultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='pathology',
            field=models.BooleanField(default=False),
        ),
    ]
