# Generated by Django 5.0.3 on 2024-05-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0090_alter_users_xrai_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='drconsultation',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sample_collection',
        ),
    ]
