# Generated by Django 3.1.3 on 2025-06-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_users_drconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='audiometry_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='drconsultation_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='ecg_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='optometry_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='pathology_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='pft_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='registration_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='sputum_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='vitals_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='xray_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
